### ISSUE TITLE
Routes generating differently than expected

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-router-generator#17]
I'm uncertain where, when, or how this started (or if this lib is even responsible for this), but routes are generating with an object for some reason.
`ember g route foo` should generate:
```
  this.route('foo');
```
but is instead generating:
```
  this.route('foo', {});
```

This is causing the blueprint tests to fail on Appveyor, and my local. I'm guessing Travis is still passing because it has the dependencies cached or something. Signs are pointing towards a dependency that changed upstream.

**Comment by rwjblue** [comment]
Possibly from https://github.com/ember-cli/ember-router-generator/pull/12? 

@marcioj - Do you think https://github.com/ember-cli/ember-router-generator/pull/12 could have caused this?

**Comment by marcioj** [comment]
@rwjblue yes I think so. Ember-cli invokes the router generator passing additional options like `{ target: 'some/path', entity: { ... }, ui: { ... } }` and so on. And [this check](https://github.com/ember-cli/ember-router-generator/blob/master/lib/helpers/route-node.js#L19) just look for some key presence which make the empty object be added. Internally ember-router-generator have to check if a valid option were passed to prevent this issue.

I'm busy right now, so I can send a fix tonight or tomorrow. Sorry for this, and thanks for report this issue!

**Comment by rwjblue** [comment]
@marcioj - Awesome, thanks for taking a look and confirming that might be the source of the issue.

@kellyselden / @trabus - We should probably lock down our version to allow AppVeyor (and non-cached `npm install`'s) to pass, what do y'all think?

**Comment by kellyselden** [comment]
@rwjblue you mean like instead of `^1.0.0`, use `~1.0.0` and essentially roll back? I think that's a good idea until this can be ironed out.

**Comment by rwjblue** [comment]
@kellyselden - I mean to use *exactly* `1.0.0` (no looseness) until a patched version is released.

**Comment by trabus** [comment]
@rwjblue :+1: to locking down.

**Comment by trabus** [comment]
If a fix comes before the release we'll just bump it back up.

**Comment by abuiles** [comment]
@trabus @rwjblue just released @marcioj fix, should be available in 1.1.1.

**Comment by trabus** [comment]
@abuiles @marcioj thanks! will bump in ember-cli.
