### ISSUE TITLE
Add support for generating `mount` or other statements

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-router-generator#20]
In working on [adding blueprints for Ember Engines](https://github.com/dgeb/ember-engines/pull/60), it seems to make sense to modify `router.js` if you are generating an in-repo routable engine ([similar to when generating a route](https://github.com/ember-cli/ember-cli/blob/master/blueprints/route/index.js#L86)). However, this would require adding a `this.mount` statement instead of the normal `this.route` to the route mappings.

Since the intention is to push support for Engines further upstream, I wanted to see if it made sense to modify ember-router-generator to support creating `this.mount` or other statements. I believe this could be accomplished by simply [changing this helper to accept an identifier option](https://github.com/ember-cli/ember-router-generator/blob/master/lib/helpers/route-node.js#L12).

**Comment by stefanpenner** [comment]
:+1:
