### ISSUE TITLE
Route blueprint with --reset-namespace flag does not generate correct file structure

### ISSUE THREAD

**Issue by tavosansal** [ember-cli/ember-router-generator#25]
When trying to generate a route like so: ```ember g route parent/child --reset-namespace```, ember-cli is using the default file structure which puts the route and template file for ```child``` inside the folder for ```parent```. This causes child route to not be found when running the application. If I take the files generated for ```child``` out of their corresponding ```parent``` folder then everything works as expected. 

I used this tool to check the file structure of my files: http://alexspeller.com/ember-diagonal

User this as input and click on the comments route. If you remove the resetNamespace then the files show as ember-cli is generating them
```
this.route('posts');
this.route('post', {path: '/posts/:post_id'}, function () {
  this.route('new');
  this.route('edit');
  this.route('comments', {
    resetNamespace: true
  }, function() {
    this.route('new');
  });
});
this.route('signup');
```

---

Output from ember version --verbose:
```
ember-cli: 2.6.2
http_parser: 2.5.0
node: 4.2.4
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
os: darwin x64
```

**Comment by stefanpenner** [comment]
@abuiles got any cycles

**Comment by abuiles** [comment]
@stefanpenner yes, I do. I'll work on this and the other pending issue tomorrow.

**Comment by tavosansal** [comment]
Thank you for looking into this

**Comment by abuiles** [comment]
@stefanpenner @tavosansal the issue is in the blueprint generator. I'll reopen the issue in ember-cli and clarify.

As for the router.js changes, it works as expected.

If I have a route like 

```
Router.map(function() {
  this.route('friends', function() {
  });
});
```

After running `ember g route friends/irresponsible --reset-namespace` it becomes:

```
Router.map(function() {
  this.route('friends', function() {
    this.route('irresponsible', {
      resetNamespace: true
    });
  });
});
```

The output is correct, what is wrong is the generated files.

The following is the output when generating the file:

```
ember g route friends/irresponsible --reset-namespace
installing route
  create app/routes/friends/irresponsible.js
  create app/templates/friends/irresponsible.hbs
updating router
  add route friends/irresponsible
installing route-test
  create tests/unit/routes/friends/irresponsible-test.js
````

But the correct output should be:

```
ember g route friends/irresponsible --reset-namespace
installing route
  create app/routes/irresponsible.js
  create app/templates/irresponsible.hbs
updating router
  add route friends/irresponsible
installing route-test
  create tests/unit/routes/irresponsible-test.js
```
