### ISSUE TITLE
Converts all single-quotes to double quotes in router.js

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-router-generator#4]
Basically any time that router.js is changed, it changes all quotes to double quotes, although by default the quotes are single-quotes.

To reproduce, create new ember-cli project, and run `ember g route test`.

**Comment by abuiles** [comment]
To support this we'll need to make a PR against recast so this option is configurable. For now it will stop changing all single quotes to double, but the new routes will have double.

**Comment by abuiles** [comment]
Fixed with https://github.com/ember-cli/ember-router-generator/commit/469509b12e453aff5f79846709feca270780a33f, it will be available in the next release of ember-cli.
